"""Init

Revision ID: 7f562963f834
Revises: 729a72da024f
Create Date: 2024-08-19 20:54:46.087494

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f562963f834'
down_revision: Union[str, None] = '729a72da024f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plates', sa.Column('total_cost', sa.Float(), nullable=True))
    op.add_column('plates', sa.Column('parking_limit', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plates', 'parking_limit')
    op.drop_column('plates', 'total_cost')
    # ### end Alembic commands ###
