"""Init

Revision ID: 838bf6f232b0
Revises: 9023dcec2b34
Create Date: 2024-08-20 21:02:38.094936

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '838bf6f232b0'
down_revision: Union[str, None] = '9023dcec2b34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parking', sa.Column('plate_id', sa.Integer(), nullable=True))
    op.drop_index('ix_parking_license_plate', table_name='parking')
    op.create_foreign_key(None, 'parking', 'plates', ['plate_id'], ['id'])
    op.drop_column('parking', 'license_plate')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parking', sa.Column('license_plate', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'parking', type_='foreignkey')
    op.create_index('ix_parking_license_plate', 'parking', ['license_plate'], unique=True)
    op.drop_column('parking', 'plate_id')
    # ### end Alembic commands ###
