"""Init

Revision ID: 9116077e33f5
Revises: b65e4c1c7153
Create Date: 2024-08-19 18:52:20.739786

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9116077e33f5'
down_revision: Union[str, None] = 'b65e4c1c7153'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cars', sa.Column('black_list', sa.Boolean(), nullable=True))
    op.add_column('cars', sa.Column('rate', sa.Float(), nullable=True))
    op.drop_column('cars', 'description')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cars', sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('cars', 'rate')
    op.drop_column('cars', 'black_list')
    # ### end Alembic commands ###
