"""Init

Revision ID: a32810027d65
Revises: 7f562963f834
Create Date: 2024-08-20 20:53:28.707282

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a32810027d65'
down_revision: Union[str, None] = '7f562963f834'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parking', sa.Column('plate_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'parking', 'plates', ['plate_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'parking', type_='foreignkey')
    op.drop_column('parking', 'plate_id')
    # ### end Alembic commands ###
