"""Init

Revision ID: d644305cf253
Revises: a32810027d65
Create Date: 2024-08-20 20:54:30.438156

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd644305cf253'
down_revision: Union[str, None] = 'a32810027d65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('parking_plate_id_fkey', 'parking', type_='foreignkey')
    op.drop_column('parking', 'plate_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parking', sa.Column('plate_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('parking_plate_id_fkey', 'parking', 'plates', ['plate_id'], ['id'])
    # ### end Alembic commands ###
